# Taken from https://github.com/ppy/osu-resources/blob/master/crowdin.yml

preserve_hierarchy: true
files:
  - source: /osu.Game.Rulesets.Tau/Localisation/Translations/**/*.resx
    translation: /osu.Game.Rulesets.Tau/Localisation/Translations/**/%file_name%.%osx_locale%.resx
    ignore:
      - /osu.Game.Rulesets.Tau/Localisation/Translations/**/%file_name%.*.%file_extension%
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        ar: ar
        be: be
        bg: bg
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        es-ES: es
        fi: fi
        fil: fil
        fr: fr
        he: he
        hu: hu
        id: id
        it: it
        ja: ja
        ko: ko
        lt: lt
        nl: nl
        'no': 'no'
        pl: pl
        pt-BR: pt-BR
        pt-PT: pt
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sr: sr
        sv-SE: sv
        th: th
        tr: tr
        uk: uk
        vi: vi
        zh-CN: zh
        zh-TW: zh-Hant
